import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useActor } from './useActor';
import { ResearchPaper } from '../backend';

export function usePaperData() {
  const { actor, isFetching } = useActor();

  return useQuery<ResearchPaper>({
    queryKey: ['researchPaper'],
    queryFn: async () => {
      if (!actor) throw new Error('Actor not initialized');
      return await actor.getResearchPaper();
    },
    enabled: !!actor && !isFetching,
  });
}

export function useCheckPaperSaved() {
  const { actor, isFetching } = useActor();

  return useQuery<boolean>({
    queryKey: ['paperSaved'],
    queryFn: async () => {
      if (!actor) return false;
      return await actor.isResearchPaperSaved();
    },
    enabled: !!actor && !isFetching,
  });
}

export function useSavePaper() {
  const { actor } = useActor();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (paper: ResearchPaper) => {
      if (!actor) throw new Error('Actor not initialized');

      await actor.saveResearchPaper(
        paper.title,
        paper.topic,
        paper.abstract,
        paper.keywords,
        paper.introduction,
        paper.governmentFramework,
        paper.factors,
        paper.comparativeAnalysis,
        paper.objectives,
        paper.literatureReview,
        paper.methodology,
        paper.dataAnalysis,
        paper.results,
        paper.discussion,
        paper.policyRecommendations,
        paper.conclusion,
        paper.citations,
        paper.author
      );
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['researchPaper'] });
      queryClient.invalidateQueries({ queryKey: ['paperSaved'] });
    },
  });
}

export function useCreatePaper() {
  const { actor } = useActor();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      title,
      author,
      researchTopic,
      keywords,
      objectives,
    }: {
      title: string;
      author: string;
      researchTopic: string;
      keywords: string[];
      objectives: string;
    }) => {
      if (!actor) throw new Error('Actor not initialized');

      // Call backend to generate the paper with AI
      const generatedPaper = await actor.createResearchPaper(
        title,
        researchTopic, // topic
        '', // abstract - will be generated by AI
        keywords,
        '', // introduction - will be generated by AI
        '', // governmentFramework - will be generated by AI
        '', // factors - will be generated by AI
        '', // comparativeAnalysis - will be generated by AI
        objectives,
        '', // literatureReview - will be generated by AI
        '', // methodology - will be generated by AI
        '', // dataAnalysis - will be generated by AI
        '', // results - will be generated by AI
        '', // discussion - will be generated by AI
        '', // policyRecommendations - will be generated by AI
        '', // conclusion - will be generated by AI
        '', // citations - will be generated by AI
        author
      );

      return generatedPaper;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['researchPaper'] });
      queryClient.invalidateQueries({ queryKey: ['paperSaved'] });
    },
    onError: (error: Error) => {
      // Extract user-friendly error message
      const errorMessage = error.message || 'Failed to generate paper';
      throw new Error(errorMessage);
    },
  });
}
