/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResearchPaper = IDL.Record({
  'governmentFramework' : IDL.Text,
  'title' : IDL.Text,
  'policyRecommendations' : IDL.Text,
  'dataAnalysis' : IDL.Text,
  'conclusion' : IDL.Text,
  'results' : IDL.Text,
  'author' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'introduction' : IDL.Text,
  'comparativeAnalysis' : IDL.Text,
  'factorsAffecting' : IDL.Text,
  'literatureReview' : IDL.Text,
  'abstract' : IDL.Text,
  'discussion' : IDL.Text,
  'citations' : IDL.Vec(IDL.Text),
  'methodology' : IDL.Text,
  'objectives' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'downloadResearchPaper' : IDL.Func([], [IDL.Text], ['query']),
  'getResearchPaper' : IDL.Func([], [ResearchPaper], ['query']),
  'getResearchPaperFields' : IDL.Func(
      [],
      [
        IDL.Record({
          'governmentFramework' : IDL.Text,
          'title' : IDL.Text,
          'policyRecommendations' : IDL.Text,
          'dataAnalysis' : IDL.Text,
          'conclusion' : IDL.Text,
          'results' : IDL.Text,
          'author' : IDL.Text,
          'keywords' : IDL.Vec(IDL.Text),
          'introduction' : IDL.Text,
          'comparativeAnalysis' : IDL.Text,
          'factorsAffecting' : IDL.Text,
          'literatureReview' : IDL.Text,
          'abstract' : IDL.Text,
          'discussion' : IDL.Text,
          'citations' : IDL.Vec(IDL.Text),
          'methodology' : IDL.Text,
          'objectives' : IDL.Vec(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'isResearchPaperSaved' : IDL.Func([], [IDL.Bool], ['query']),
  'saveResearchPaper' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResearchPaper = IDL.Record({
    'governmentFramework' : IDL.Text,
    'title' : IDL.Text,
    'policyRecommendations' : IDL.Text,
    'dataAnalysis' : IDL.Text,
    'conclusion' : IDL.Text,
    'results' : IDL.Text,
    'author' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'introduction' : IDL.Text,
    'comparativeAnalysis' : IDL.Text,
    'factorsAffecting' : IDL.Text,
    'literatureReview' : IDL.Text,
    'abstract' : IDL.Text,
    'discussion' : IDL.Text,
    'citations' : IDL.Vec(IDL.Text),
    'methodology' : IDL.Text,
    'objectives' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'downloadResearchPaper' : IDL.Func([], [IDL.Text], ['query']),
    'getResearchPaper' : IDL.Func([], [ResearchPaper], ['query']),
    'getResearchPaperFields' : IDL.Func(
        [],
        [
          IDL.Record({
            'governmentFramework' : IDL.Text,
            'title' : IDL.Text,
            'policyRecommendations' : IDL.Text,
            'dataAnalysis' : IDL.Text,
            'conclusion' : IDL.Text,
            'results' : IDL.Text,
            'author' : IDL.Text,
            'keywords' : IDL.Vec(IDL.Text),
            'introduction' : IDL.Text,
            'comparativeAnalysis' : IDL.Text,
            'factorsAffecting' : IDL.Text,
            'literatureReview' : IDL.Text,
            'abstract' : IDL.Text,
            'discussion' : IDL.Text,
            'citations' : IDL.Vec(IDL.Text),
            'methodology' : IDL.Text,
            'objectives' : IDL.Vec(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'isResearchPaperSaved' : IDL.Func([], [IDL.Bool], ['query']),
    'saveResearchPaper' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };