/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResearchPaper = IDL.Record({
  'governmentFramework' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'wordCount' : IDL.Nat,
  'policyRecommendations' : IDL.Text,
  'dataAnalysis' : IDL.Text,
  'createdAt' : IDL.Int,
  'conclusion' : IDL.Text,
  'results' : IDL.Text,
  'author' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'introduction' : IDL.Text,
  'comparativeAnalysis' : IDL.Text,
  'literatureReview' : IDL.Text,
  'factors' : IDL.Text,
  'abstract' : IDL.Text,
  'discussion' : IDL.Text,
  'citations' : IDL.Text,
  'methodology' : IDL.Text,
  'objectives' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createResearchPaper' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [ResearchPaper],
      [],
    ),
  'downloadResearchPaper' : IDL.Func([], [IDL.Text], ['query']),
  'getAccessHistory' : IDL.Func([], [IDL.Vec(IDL.Int)], ['query']),
  'getApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getResearchPaper' : IDL.Func([], [ResearchPaper], ['query']),
  'getResearchPaperFields' : IDL.Func(
      [],
      [
        IDL.Record({
          'governmentFramework' : IDL.Text,
          'title' : IDL.Text,
          'topic' : IDL.Text,
          'wordCount' : IDL.Nat,
          'policyRecommendations' : IDL.Text,
          'dataAnalysis' : IDL.Text,
          'createdAt' : IDL.Int,
          'conclusion' : IDL.Text,
          'results' : IDL.Text,
          'author' : IDL.Text,
          'keywords' : IDL.Vec(IDL.Text),
          'introduction' : IDL.Text,
          'comparativeAnalysis' : IDL.Text,
          'literatureReview' : IDL.Text,
          'factors' : IDL.Text,
          'abstract' : IDL.Text,
          'discussion' : IDL.Text,
          'citations' : IDL.Text,
          'methodology' : IDL.Text,
          'objectives' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'isResearchPaperSaved' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAccess' : IDL.Func([], [], []),
  'saveResearchPaper' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResearchPaper = IDL.Record({
    'governmentFramework' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'wordCount' : IDL.Nat,
    'policyRecommendations' : IDL.Text,
    'dataAnalysis' : IDL.Text,
    'createdAt' : IDL.Int,
    'conclusion' : IDL.Text,
    'results' : IDL.Text,
    'author' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'introduction' : IDL.Text,
    'comparativeAnalysis' : IDL.Text,
    'literatureReview' : IDL.Text,
    'factors' : IDL.Text,
    'abstract' : IDL.Text,
    'discussion' : IDL.Text,
    'citations' : IDL.Text,
    'methodology' : IDL.Text,
    'objectives' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createResearchPaper' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [ResearchPaper],
        [],
      ),
    'downloadResearchPaper' : IDL.Func([], [IDL.Text], ['query']),
    'getAccessHistory' : IDL.Func([], [IDL.Vec(IDL.Int)], ['query']),
    'getApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getResearchPaper' : IDL.Func([], [ResearchPaper], ['query']),
    'getResearchPaperFields' : IDL.Func(
        [],
        [
          IDL.Record({
            'governmentFramework' : IDL.Text,
            'title' : IDL.Text,
            'topic' : IDL.Text,
            'wordCount' : IDL.Nat,
            'policyRecommendations' : IDL.Text,
            'dataAnalysis' : IDL.Text,
            'createdAt' : IDL.Int,
            'conclusion' : IDL.Text,
            'results' : IDL.Text,
            'author' : IDL.Text,
            'keywords' : IDL.Vec(IDL.Text),
            'introduction' : IDL.Text,
            'comparativeAnalysis' : IDL.Text,
            'literatureReview' : IDL.Text,
            'factors' : IDL.Text,
            'abstract' : IDL.Text,
            'discussion' : IDL.Text,
            'citations' : IDL.Text,
            'methodology' : IDL.Text,
            'objectives' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'isResearchPaperSaved' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAccess' : IDL.Func([], [], []),
    'saveResearchPaper' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };