/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ResearchPaper {
  'governmentFramework' : string,
  'title' : string,
  'policyRecommendations' : string,
  'dataAnalysis' : string,
  'conclusion' : string,
  'results' : string,
  'author' : string,
  'keywords' : Array<string>,
  'introduction' : string,
  'comparativeAnalysis' : string,
  'factorsAffecting' : string,
  'literatureReview' : string,
  'abstract' : string,
  'discussion' : string,
  'citations' : Array<string>,
  'methodology' : string,
  'objectives' : Array<string>,
}
export interface _SERVICE {
  'downloadResearchPaper' : ActorMethod<[], string>,
  'getResearchPaper' : ActorMethod<[], ResearchPaper>,
  'getResearchPaperFields' : ActorMethod<
    [],
    {
      'governmentFramework' : string,
      'title' : string,
      'policyRecommendations' : string,
      'dataAnalysis' : string,
      'conclusion' : string,
      'results' : string,
      'author' : string,
      'keywords' : Array<string>,
      'introduction' : string,
      'comparativeAnalysis' : string,
      'factorsAffecting' : string,
      'literatureReview' : string,
      'abstract' : string,
      'discussion' : string,
      'citations' : Array<string>,
      'methodology' : string,
      'objectives' : Array<string>,
    }
  >,
  'isResearchPaperSaved' : ActorMethod<[], boolean>,
  'saveResearchPaper' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];