/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ResearchPaper {
  'governmentFramework' : string,
  'title' : string,
  'topic' : string,
  'wordCount' : bigint,
  'policyRecommendations' : string,
  'dataAnalysis' : string,
  'createdAt' : bigint,
  'conclusion' : string,
  'results' : string,
  'author' : string,
  'keywords' : Array<string>,
  'introduction' : string,
  'comparativeAnalysis' : string,
  'literatureReview' : string,
  'factors' : string,
  'abstract' : string,
  'discussion' : string,
  'citations' : string,
  'methodology' : string,
  'objectives' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createResearchPaper' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    ResearchPaper
  >,
  'downloadResearchPaper' : ActorMethod<[], string>,
  'getAccessHistory' : ActorMethod<[], Array<bigint>>,
  'getApiKey' : ActorMethod<[], string>,
  'getResearchPaper' : ActorMethod<[], ResearchPaper>,
  'getResearchPaperFields' : ActorMethod<
    [],
    {
      'governmentFramework' : string,
      'title' : string,
      'topic' : string,
      'wordCount' : bigint,
      'policyRecommendations' : string,
      'dataAnalysis' : string,
      'createdAt' : bigint,
      'conclusion' : string,
      'results' : string,
      'author' : string,
      'keywords' : Array<string>,
      'introduction' : string,
      'comparativeAnalysis' : string,
      'literatureReview' : string,
      'factors' : string,
      'abstract' : string,
      'discussion' : string,
      'citations' : string,
      'methodology' : string,
      'objectives' : string,
    }
  >,
  'isResearchPaperSaved' : ActorMethod<[], boolean>,
  'recordAccess' : ActorMethod<[], undefined>,
  'saveResearchPaper' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];