/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ResearchPaper {
    governmentFramework: string;
    title: string;
    topic: string;
    wordCount: bigint;
    policyRecommendations: string;
    dataAnalysis: string;
    createdAt: bigint;
    conclusion: string;
    results: string;
    author: string;
    keywords: Array<string>;
    introduction: string;
    comparativeAnalysis: string;
    literatureReview: string;
    factors: string;
    abstract: string;
    discussion: string;
    citations: string;
    methodology: string;
    objectives: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    createResearchPaper(title: string, topic: string, abstract: string, keywords: Array<string>, introduction: string, governmentFramework: string, factors: string, comparativeAnalysis: string, objectives: string, literatureReview: string, methodology: string, dataAnalysis: string, results: string, discussion: string, policyRecommendations: string, conclusion: string, citations: string, author: string): Promise<ResearchPaper>;
    downloadResearchPaper(): Promise<string>;
    getAccessHistory(): Promise<Array<bigint>>;
    getApiKey(): Promise<string>;
    getResearchPaper(): Promise<ResearchPaper>;
    getResearchPaperFields(): Promise<{
        governmentFramework: string;
        title: string;
        topic: string;
        wordCount: bigint;
        policyRecommendations: string;
        dataAnalysis: string;
        createdAt: bigint;
        conclusion: string;
        results: string;
        author: string;
        keywords: Array<string>;
        introduction: string;
        comparativeAnalysis: string;
        literatureReview: string;
        factors: string;
        abstract: string;
        discussion: string;
        citations: string;
        methodology: string;
        objectives: string;
    }>;
    isResearchPaperSaved(): Promise<boolean>;
    recordAccess(): Promise<void>;
    saveResearchPaper(title: string, topic: string, abstract: string, keywords: Array<string>, introduction: string, governmentFramework: string, factors: string, comparativeAnalysis: string, objectives: string, literatureReview: string, methodology: string, dataAnalysis: string, results: string, discussion: string, policyRecommendations: string, conclusion: string, citations: string, author: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createResearchPaper(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string, arg14: string, arg15: string, arg16: string, arg17: string): Promise<ResearchPaper> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearchPaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearchPaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async downloadResearchPaper(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadResearchPaper();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadResearchPaper();
            return result;
        }
    }
    async getAccessHistory(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessHistory();
            return result;
        }
    }
    async getApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiKey();
            return result;
        }
    }
    async getResearchPaper(): Promise<ResearchPaper> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchPaper();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchPaper();
            return result;
        }
    }
    async getResearchPaperFields(): Promise<{
        governmentFramework: string;
        title: string;
        topic: string;
        wordCount: bigint;
        policyRecommendations: string;
        dataAnalysis: string;
        createdAt: bigint;
        conclusion: string;
        results: string;
        author: string;
        keywords: Array<string>;
        introduction: string;
        comparativeAnalysis: string;
        literatureReview: string;
        factors: string;
        abstract: string;
        discussion: string;
        citations: string;
        methodology: string;
        objectives: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchPaperFields();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchPaperFields();
            return result;
        }
    }
    async isResearchPaperSaved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isResearchPaperSaved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isResearchPaperSaved();
            return result;
        }
    }
    async recordAccess(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAccess();
            return result;
        }
    }
    async saveResearchPaper(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string, arg14: string, arg15: string, arg16: string, arg17: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResearchPaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResearchPaper(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
